version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
